# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Zach Larsen
tagline:          'Programmer Extraordinaire'
description:      'Programmer Extraordinaire'
url:              http://zachariahlarsen.com
baseurl:          /

author:
  name:           'Zach Larsen'
  url:            https://twitter.com/zlarsenz

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/zachcustombit

pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'
